# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dec_exec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65\x63_exec.proto\x12\x08\x64\x65\x63_exec\"s\n\x03\x41pp\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x0f\n\x07\x61pp_uid\x18\x02 \x01(\x03\x12\x11\n\tfunc_name\x18\x03 \x01(\t\x12\x10\n\x08in_files\x18\x04 \x03(\t\x12\x11\n\tout_files\x18\x05 \x03(\t\x12\x11\n\tclient_id\x18\x06 \x01(\t\"3\n\x04\x42lob\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x0c\x12\x11\n\tclient_id\x18\x03 \x01(\t\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\t2\x98\x01\n\x07\x44\x65\x63\x45xec\x12)\n\x04\x45xec\x12\r.dec_exec.App\x1a\x10.dec_exec.Result\"\x00\x12\x30\n\nUploadBlob\x12\x0e.dec_exec.Blob\x1a\x10.dec_exec.Result\"\x00\x12\x30\n\x0cRetrieveBlob\x12\x0e.dec_exec.Blob\x1a\x0e.dec_exec.Blob\"\x00\x42/\n\x17io.grpc.dtrust.dec_execB\x0c\x44\x65\x63\x45xecProtoP\x01\xa2\x02\x03\x44TEb\x06proto3')



_APP = DESCRIPTOR.message_types_by_name['App']
_BLOB = DESCRIPTOR.message_types_by_name['Blob']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
App = _reflection.GeneratedProtocolMessageType('App', (_message.Message,), {
  'DESCRIPTOR' : _APP,
  '__module__' : 'dec_exec_pb2'
  # @@protoc_insertion_point(class_scope:dec_exec.App)
  })
_sym_db.RegisterMessage(App)

Blob = _reflection.GeneratedProtocolMessageType('Blob', (_message.Message,), {
  'DESCRIPTOR' : _BLOB,
  '__module__' : 'dec_exec_pb2'
  # @@protoc_insertion_point(class_scope:dec_exec.Blob)
  })
_sym_db.RegisterMessage(Blob)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'dec_exec_pb2'
  # @@protoc_insertion_point(class_scope:dec_exec.Result)
  })
_sym_db.RegisterMessage(Result)

_DECEXEC = DESCRIPTOR.services_by_name['DecExec']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.grpc.dtrust.dec_execB\014DecExecProtoP\001\242\002\003DTE'
  _APP._serialized_start=28
  _APP._serialized_end=143
  _BLOB._serialized_start=145
  _BLOB._serialized_end=196
  _RESULT._serialized_start=198
  _RESULT._serialized_end=222
  _DECEXEC._serialized_start=225
  _DECEXEC._serialized_end=377
# @@protoc_insertion_point(module_scope)
