# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dec_exec_pb2 as dec__exec__pb2


class DecExecStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_unary(
                '/dec_exec.DecExec/Exec',
                request_serializer=dec__exec__pb2.App.SerializeToString,
                response_deserializer=dec__exec__pb2.Result.FromString,
                )
        self.UploadBlob = channel.unary_unary(
                '/dec_exec.DecExec/UploadBlob',
                request_serializer=dec__exec__pb2.Blob.SerializeToString,
                response_deserializer=dec__exec__pb2.Result.FromString,
                )
        self.RetrieveBlob = channel.unary_unary(
                '/dec_exec.DecExec/RetrieveBlob',
                request_serializer=dec__exec__pb2.Blob.SerializeToString,
                response_deserializer=dec__exec__pb2.Blob.FromString,
                )


class DecExecServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecExecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=dec__exec__pb2.App.FromString,
                    response_serializer=dec__exec__pb2.Result.SerializeToString,
            ),
            'UploadBlob': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadBlob,
                    request_deserializer=dec__exec__pb2.Blob.FromString,
                    response_serializer=dec__exec__pb2.Result.SerializeToString,
            ),
            'RetrieveBlob': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveBlob,
                    request_deserializer=dec__exec__pb2.Blob.FromString,
                    response_serializer=dec__exec__pb2.Blob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dec_exec.DecExec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DecExec(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dec_exec.DecExec/Exec',
            dec__exec__pb2.App.SerializeToString,
            dec__exec__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dec_exec.DecExec/UploadBlob',
            dec__exec__pb2.Blob.SerializeToString,
            dec__exec__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dec_exec.DecExec/RetrieveBlob',
            dec__exec__pb2.Blob.SerializeToString,
            dec__exec__pb2.Blob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
